'use strict';
let products=[];
const $=id=>document.getElementById(id);
const money=n=>Number(n).toLocaleString('ru-RU')+' ₽';
let category='Все',limit=12,selected=null,lastFocus=null;
const dialog=$('product-dialog');
function node(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;}
function placeholder(){const d=node('div','picture placeholder');d.append(node('span','monogram','цб'),node('small','','Фотография скоро'));return d;}
function picture(p){if(!p.image)return placeholder();const d=node('div','picture');const img=node('img');img.src=p.image;img.alt=p.name;img.loading='lazy';img.addEventListener('error',()=>d.replaceWith(placeholder()),{once:true});d.append(img);return d;}
function card(p){const article=node('article','product');const open=node('button','product-open');open.type='button';open.setAttribute('aria-label','Открыть: '+p.name);open.append(picture(p),node('span','product-meta',p.category),node('h3','',p.name));open.addEventListener('click',()=>openProduct(p));const bottom=node('div','product-bottom');bottom.append(node('span','',p.price>0?money(p.price)+(p.unit?' / шт.':''):'Цена по запросу'));const b=node('button','','Подробнее');b.type='button';b.setAttribute('aria-label','Подробнее: '+p.name);b.onclick=()=>openProduct(p);bottom.append(b);article.append(open,bottom);return article;}
function renderCategories(){const preferred=['Букеты','Розы','Срезанные цветы','Сезонные','Композиции','Растения'];const existing=[...new Set(products.map(p=>p.category).filter(Boolean))];const cats=['Все',...preferred.filter(c=>existing.includes(c)),...existing.filter(c=>!preferred.includes(c)).sort((a,b)=>a.localeCompare(b,'ru'))];$('categories').replaceChildren(...cats.map(c=>{const b=node('button',category===c?'active':'',c);b.type='button';b.setAttribute('aria-pressed',String(category===c));b.onclick=()=>{category=c;limit=12;renderCategories();renderProducts();};return b;}));}
function renderProducts(){const q=$('search').value.trim().toLocaleLowerCase('ru');const result=products.filter(p=>(category==='Все'||p.category===category)&&p.name.toLocaleLowerCase('ru').includes(q));$('products').replaceChildren(...result.slice(0,limit).map(card));if(!result.length)$('products').append(node('p','empty','Ничего не найдено. Попробуйте другое название или категорию.'));$('count').textContent='Показано '+Math.min(limit,result.length)+' из '+result.length;$('more').hidden=limit>=result.length;}
function quantity(){const v=Number($('quantity').value);return Number.isFinite(v)?Math.min(999,Math.max(1,Math.floor(v))):1;}
function updateOrder(){if(!selected)return;const qty=selected.unit?quantity():1;const text='Здравствуйте! Хочу заказать: '+selected.name+(selected.unit?' — '+qty+' шт.':'.')+' Подскажите, пожалуйста, наличие и итоговую стоимость.';$('order-text').value=text;const vkBase=window.CMS_VK_URL||'https://vk.ru/im?sel=-61006706';$('order').href=vkBase+(vkBase.includes('?')?'&':'?')+'text='+encodeURIComponent(text);$('detail-price').textContent=selected.price>0?(selected.unit?money(selected.price*qty)+' · '+money(selected.price)+' / шт.':money(selected.price)):'Цена по запросу';$('minus').disabled=qty<=1;$('plus').disabled=qty>=999;$('copy-status').textContent='';}
function openProduct(p){selected=p;lastFocus=document.activeElement;$('detail-picture').replaceChildren(picture(p));$('detail-name').textContent=p.name;$('detail-category').textContent=p.category;$('detail-description').textContent=p.description||(p.unit?'Выберите количество цветов. Оттенок, длину стебля, упаковку и наличие уточнит флорист.':'Состав, оформление и актуальное наличие уточните у флориста перед заказом.');$('quantity-block').hidden=!p.unit;$('quantity').value=p.unit?11:1;$('order').textContent=p.available===false?'Уточнить поступление во ВКонтакте':'Заказать во ВКонтакте';updateOrder();dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');$('close-dialog').focus({preventScroll:true});}
$('close-dialog').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(lastFocus)lastFocus.focus({preventScroll:true});});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
$('quantity').addEventListener('input',updateOrder);$('quantity').addEventListener('change',()=>{$('quantity').value=quantity();updateOrder();});$('minus').onclick=()=>{$('quantity').value=Math.max(1,quantity()-1);updateOrder();};$('plus').onclick=()=>{$('quantity').value=Math.min(999,quantity()+1);updateOrder();};document.querySelectorAll('[data-quantity]').forEach(b=>b.onclick=()=>{$('quantity').value=b.dataset.quantity;updateOrder();});
async function copyOrder(){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText($('order-text').value);}else{$('order-text').focus();$('order-text').select();if(!document.execCommand('copy'))throw new Error('copy unavailable');}$('copy-status').textContent='Текст скопирован — можно вставить в ВК.';}catch{$('order-text').focus();$('order-text').select();$('copy-status').textContent='Выделите и скопируйте сообщение вручную.';}}
$('copy').onclick=copyOrder;
$('search').addEventListener('input',()=>{limit=12;renderProducts();});$('more').onclick=()=>{limit+=12;renderProducts();};
const menu=document.querySelector('.menu');menu.onclick=()=>{const open=$('nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open));};$('nav').querySelectorAll('a').forEach(a=>a.onclick=()=>{$('nav').classList.remove('open');menu.setAttribute('aria-expanded','false');});
document.querySelectorAll('.map-link').forEach(a=>{a.href='https://yandex.ru/maps/?text='+encodeURIComponent('Цвет-База.рф '+a.dataset.address);a.target='_blank';a.rel='noopener';});
const care=[['Базовые правила','Вымойте вазу и налейте чистую прохладную воду. Обновите срез на 1–2 см острым инструментом, удалите листья ниже уровня воды. Регулярно меняйте воду и мойте вазу. Держите букет вдали от батарей, прямого солнца и спелых фруктов.'],['Розы','Обновите срез на 2–3 см, удалите нижние листья. Следите за достаточным уровнем чистой прохладной воды и регулярно мойте вазу.'],['Тюльпаны','Тюльпаны продолжают расти после срезки и тянутся к свету. Налейте немного прохладной воды, ежедневно меняйте её и проверяйте уровень. Не ставьте букет в жаркое место.'],['Хризантемы','Удалите нижние листья, обновите срез и регулярно меняйте воду. Не ставьте цветы возле отопительных приборов.'],['Гортензии','Гортензии чувствительны к недостатку воды. Поддерживайте достаточный уровень воды в чистой вазе, обновляйте срез и не допускайте пересыхания.'],['Сборные букеты и композиции','Поддерживайте воду чистой и обновляйте срезы каждые 1–2 дня. Если композиция собрана на флористической губке, не вытаскивайте цветы: понемногу доливайте воду в губку.']];care.forEach(([title,text],i)=>{const d=node('details');d.append(node('summary','',title),node('p','',text));if(i===0)d.open=true;$('care-list').append(d);});
async function initCatalog(){
  try{if(window.PRODUCTS_READY)await window.PRODUCTS_READY;}catch(e){console.warn(e);}
  products=(Array.isArray(window.PRODUCTS)?window.PRODUCTS:[]).filter(p=>p.published!==false);
  const featured=products.filter(p=>p.featured).sort((a,b)=>(a.featured_order??999)-(b.featured_order??999)||(a.sort_order??100)-(b.sort_order??100));
  $('featured').replaceChildren(...(featured.length?featured:products.filter(p=>p.image)).slice(0,4).map(card));
  $('year').textContent=new Date().getFullYear();renderCategories();renderProducts();
}
initCatalog();
